[package]
name = "brute-force"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manarimo-lib = { path = "../manarimo-lib" }
rayon = "1.5.1"
serde_json = "1.0.64"
